[tool.black]
line-length = 120
skip-string-normalization = true
exclude = '''
  migrations
'''

[tool.isort]
line_length = 120
known_django = "django"
known_wagtail = "wagtail"
sections = ["FUTURE","STDLIB","DJANGO","WAGTAIL","THIRDPARTY","FIRSTPARTY","LOCALFOLDER"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
exclude = 'migrations'
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "config.settings.test"
