# Generated by Django 4.0.1 on 2022-01-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('account_type', models.CharField(max_length=255, verbose_name='account_type')),
                ('account_subtype', models.CharField(blank=True, max_length=255, verbose_name='account_subtype')),
                ('plaid_account_id', models.CharField(blank=True, max_length=255, verbose_name='plaid_account_id')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('plaid_institution_id', models.CharField(blank=True, max_length=255, verbose_name='plaid_institution_id')),
                ('plaid_access_token', models.CharField(blank=True, max_length=255, verbose_name='plaid_access_token')),
            ],
        ),
    ]
