name: Deploy To UAT
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      HEROKU_API_KEY:
        required: true

env:
  SOURCE_CONTAINER_REGISTRY: ghcr.io # we already have a build image here from running tests
  HEROKU_APP_NAME: wyzplan-staging
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

jobs:
  deploy:
    name: Deploy To UAT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract Branch Name
        uses: ./.github/actions/extract-branch-name
        id: extract_branch
      - name: Ensure Valid Branch For Environment
        if: ${{ !startsWith(steps.extract_branch.outputs.branch,'release-') }}
        shell: bash
        run: exit 1
      - name: Log in to source container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.SOURCE_CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull Source Image
        id: pull-source-image
        uses: ./.github/actions/setup-docker-image
        with:
          pull-image:  ${{ env.SOURCE_CONTAINER_REGISTRY}}/${GITHUB_REPOSITORY,,}:${{ steps.extract_branch.outputs.branch-slug }}_${GITHUB_SHA}
      - name: Deploy
        uses: ./.github/actions/heroku-container-deploy
        with:
          source-image: ${{ steps.pull-source-image.outputs.pulled-image-name }}
          heroku-app-name: ${{ env.HEROKU_APP_NAME }}
          environment-url: "https://wyzplan-staging.herokuapp.com/"
          github-token: ${{ secrets.GITHUB_TOKEN }}
